apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  namespace: ns-seminar-spring-boot
spec:
  selector:
    app: spring-boot
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31080
  type: NodePort