server:
  port: 8080

spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ${POSTGRESQL_URLL}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver