name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot app
        working-directory: backend
        run: ./gradlew clean build

      - name: Get short commit SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-boot-seminar:${{ env.SHORT_SHA }} backend
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-seminar:${{ env.SHORT_SHA }}

      - name: Update image tag in deployment.yaml
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/spring-boot-seminar:${{ env.SHORT_SHA }}|" manifests/spring-boot/deployment.yaml

      - name: Commit updated deployment.yaml
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add manifests/spring-boot/deployment.yaml
          git commit -m "chore: update image tag to ${{ env.SHORT_SHA }}"
          git push
